# Please see the notes for developers for more information about this project's
#   policy in regards to the use of git hooks.  For more information about the
#   pre-commit framework, please see: https://pre-commit.com
#
# To get started with them is this project yourself, simply run: pre-commit

repos:

  # Ensure that revisions for tools such as black, flake8, isort etc. can be
  #   managed by Poetry but synced here before commiting code
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 0.4.0
    hooks:
      - id: sync_with_poetry

  # Make sure the Poetry project is properly maintained
  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.2
    hooks:
      - id: poetry-check
      - id: poetry-lock

  # Code formatter
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black

  # Keep Python import statements organised
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  # Some minor quality of life things
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
