# .readthedocs.yml
version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - . "$(pwd | rev | sed 's/stuokcehc/svne/' | rev)/bin/activate" && poetry install --without dev -E docs
      - make apidoc
sphinx:
  configuration: docs/conf.py
