# .readthedocs.yml
version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  apt_packages:
    - mpich # Rombus has a dependency on mpi4py, which needs this
  jobs:
    post_create_environment:
      # Install pipx; this is needed because of this issue:
      #  https://github.com/python-poetry/poetry/issues/4493
      - pip install pipx
      - export PATH=${PATH}:${HOME}/.local/bin
      - echo "HOME:"${HOME}
      - echo "PATH:"${PATH}
      # Install poetry
      - pipx install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies with 'docs' dependency group
      - poetry install --without dev -E docs
      # Generate the API documentation
      - make apidoc
sphinx:
  configuration: docs/conf.py
