name: Bump version in git

on:
  pull_request:
    types: [closed]
    branches: [ $default-branch ]
jobs:
  if_merged:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Bump version
      run: |
        git config --global user.email "github+actions@gmail.com"
        git config --global user.name "Actions"
        git fetch --force --tags # needed to get the version tag; see https://github.com/actions/checkout/issues/290
        wget -O - https://raw.githubusercontent.com/treeder/bump/master/gitbump.sh | bash
