name: Bump version in git

on:
  push:
    branches:
    - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:

      - name: Check-out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Config git
        run: |
          git config --global user.email "github+actions@gmail.com"
          git config --global user.name "Actions"
          echo "0: ${{github}}"
          echo "A: ${{github.event.push}}"
          echo "B: ${{github.event.push.head_commit}}"
          echo "C: ${{github.event.push.head_commit.message}}"

      - name: Bump major
        if: contains(github.event.push.head_commit.message, '[version:major]')
        run: .github/workflows/bump.sh major

      - name: Bump minor
        if: contains(github.event.push.head_commit.message, '[version:minor]')
        run: .github/workflows/bump.sh minor

      - name: Bump patch
        if: "!contains(github.event.push.head_commit.message, '[version:major]') && !contains(github.event.push.head_commit.message, '[version:minor]')"
        run: .github/workflows/bump.sh patch
