name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:

    # Dependencies
    - name: Check-out repo
      uses: actions/checkout@v3
      run: git fetch --force --tags # needed to get the version tag; see https://github.com/actions/checkout/issues/290

    - name: Set-up MPI
      uses: mpi4py/setup-mpi@v1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Update PIP
      run: |
        python -m pip install --upgrade pip

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    # Configure project
    - name: Set project version
      run: |
        poetry version $(git describe --tags --abbrev=0)

    - name: Install the project
      run: |
        poetry install --no-interaction --extras docs

    # Run tests
    - name: Generate build
      run: |
        poetry build

    - name: Code tests
      run: |
        poetry run pytest 

    - name: Documentation build test
      run: |
        poetry run make html
